name: playstation_manager
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  gap: ^3.0.1
  easy_localization: ^3.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  get_it: ^9.2.1
  flutter_secure_storage: ^10.3.1
  vector_graphics: ^1.1.19
  objectbox: ^5.3.2
  objectbox_flutter_libs: ^5.3.2
  uuid: ^4.5.3
  skeletonizer: ^2.1.3
  dropdown_button2: ^3.1.0
  fpdart: ^1.2.0
  file_picker: ^11.0.2
  path: ^1.9.1
  path_provider: ^2.1.5
  supabase_flutter: ^2.14.2
  url_launcher: ^6.3.2
  flutter_animate: ^4.5.2
  window_manager: ^0.5.1
  clock: ^1.1.2
  lottie: ^3.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  watcher: ^1.2.1
  vector_graphics_compiler: ^1.1.19
  objectbox_generator: ^5.3.2
  build_runner: ^2.15.0

flutter_assets:
  assets_path: assets/
  output_path: lib/core/constants/
  filename: app_assets.dart
  field_prefix: null
  ignore_comments: true

  format:
    use_part_of: false
    use_const: true
    use_static: true
    style: camelCase

  named_assets:
    - path: assets/icons/vec/
      class_name: VectorIcons
      package_parameter_enabled: false
      style: camelCase

    - path: assets/images/
      class_name: AppImages
      package_parameter_enabled: false
      style: camelCase

    - path: assets/lottie/
      class_name: AppLottie
      package_parameter_enabled: false
      style: camelCase

    - path: assets/translations/
      class_name: AppTranslations
      package_parameter_enabled: false
      style: camelCase

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/vec/
    - assets/images/
    - assets/lottie/
    - assets/translations/

  fonts:
    - family: Al Jazeera Arabic
      fonts:
        - asset: assets/fonts/Al Jazeera Arabic Regular.ttf
          weight: 400
        - asset: assets/fonts/Al Jazeera Arabic Bold.ttf
          weight: 700
    - family: "NotoSansArabic"
      fonts:
        - asset: assets/fonts/NotoSansArabic.ttf
          weight: 500
