// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../../features/customers/data/models/customer_model.dart';
import '../../features/devices/data/models/device_model.dart';
import '../../features/invoices/data/models/create_invoice_model.dart';
import '../../features/storage/data/models/storage_model.dart';
import '../../features/transactions/data/models/transaction_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 5289264950159129193),
    name: 'StorageModel',
    lastPropertyId: const obx_int.IdUid(11, 21842510579154777),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 899342902428998748),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7674909582053156588),
        name: 'uuid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(7, 8837941897921877262),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2082650109279556433),
        name: 'itemName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6097370077058438972),
        name: 'itemImage',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8413942245927625467),
        name: 'quantity',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7077197220714972444),
        name: 'buyPrice',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 878786843833408149),
        name: 'sellPrice',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8973605815734033042),
        name: 'minAmount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 669552685581241048),
        name: 'typeIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 21842510579154777),
        name: 'paidAmount',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 9208822990900752414),
    name: 'CustomerModel',
    lastPropertyId: const obx_int.IdUid(9, 748095765277656098),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 190585415310064296),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1309801374550826709),
        name: 'uuid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(4, 6427761274423895429),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 423883756646716996),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8241765832006033816),
        name: 'phone1',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5085124145233156954),
        name: 'phone2',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 9027356387153805910),
        name: 'address',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 137311694524982277),
        name: 'receivableAmount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 748095765277656098),
        name: 'payableAmount',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 3415304222025532929),
    name: 'CreateInvoiceModel',
    lastPropertyId: const obx_int.IdUid(12, 1914880427519149473),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2057458220802821875),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4198074042670456661),
        name: 'uuid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(8, 7607332561444127662),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3784651634678198525),
        name: 'totalInvoice',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8575457510512860908),
        name: 'cashPaid',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2368253504708199285),
        name: 'laterPaid',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4444633202267406207),
        name: 'invoiceDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6233315288929262330),
        name: 'paymentIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8688011188511956793),
        name: 'customerId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(9, 677536105293545062),
        relationField: 'customer',
        relationTarget: 'CustomerModel',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8060014244078331336),
        name: 'isSession',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 6480102315715244152),
        name: 'sessionStartDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 2870216539185637800),
        name: 'hourlyRate',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 1914880427519149473),
        name: 'deviceId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(14, 270546992311053501),
        relationField: 'device',
        relationTarget: 'DeviceModel',
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(1, 7402174192306668538),
        name: 'items',
        targetId: const obx_int.IdUid(7, 1606597934801876537),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 1606597934801876537),
    name: 'ItemsInvoice',
    lastPropertyId: const obx_int.IdUid(5, 8660811941122145041),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2107347778151004175),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8045338546582942720),
        name: 'sellPrice',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5702608688327995180),
        name: 'quantity',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7818387833869484809),
        name: 'totalItemPrice',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8660811941122145041),
        name: 'storageItemId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(10, 4213817622721936743),
        relationField: 'storageItem',
        relationTarget: 'StorageModel',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(8, 1717198745578238179),
    name: 'TransactionModel',
    lastPropertyId: const obx_int.IdUid(14, 5948438757936141756),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 243057304441581654),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5852752717266437970),
        name: 'uuid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(11, 2912864994017705877),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4201470090141938424),
        name: 'userUuid',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2909643137126638181),
        name: 'paymentAmount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2515003860475023628),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6028283212541067497),
        name: 'notes',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6521805011368747146),
        name: 'transactionType',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2936510437728316714),
        name: 'beginningBalance',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7618314127658819307),
        name: 'endBalance',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 967054690826890390),
        name: 'invoiceProfit',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 1830679829529419815),
        name: 'paidInvoiceAmount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 417078565279352849),
        name: 'userType',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 7401941274657716944),
        name: 'userName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 5948438757936141756),
        name: 'storageItemUuid',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(10, 7788442270770736492),
    name: 'DeviceModel',
    lastPropertyId: const obx_int.IdUid(6, 23527093261008010),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3164485307514010293),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 957731370859167177),
        name: 'uuid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(13, 407330814124789583),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3287815791081424615),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2641153295362104383),
        name: 'hourlyRate',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3911512187563755874),
        name: 'typeIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 23527093261008010),
        name: 'statusIndex',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(10, 7788442270770736492),
    lastIndexId: const obx_int.IdUid(14, 270546992311053501),
    lastRelationId: const obx_int.IdUid(1, 7402174192306668538),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [
      2012309038458918598,
      8674895074077432270,
      8948141875499663187,
      4273291940691690034,
    ],
    retiredIndexUids: const [6194880861001699693],
    retiredPropertyUids: const [
      6752771352222774177,
      6600573847016762379,
      2586518660551763223,
      4822826251158611448,
      3227327288925793807,
      8522538787933854002,
      3985744442807330365,
      3235544059913130980,
      327182763463604414,
      2901761758646562592,
      6734003741869660769,
      8695103337163344616,
      2794872322145582272,
      3461668941822703355,
      5479368148903129344,
      4230486654202284661,
      278478852885223230,
      2479249803289863599,
      6667440752228361409,
      6097898792577330959,
      9045011200947960786,
      3499094377915928917,
      3165491715114893339,
      2773011440841409106,
      3202531933537570339,
      5974118554154761449,
      726372674585929937,
      2527472329238900313,
      7547018738617588892,
      4448233346927128527,
      991584696007250421,
      318772651636078351,
      7380027613144447262,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    StorageModel: obx_int.EntityDefinition<StorageModel>(
      model: _entities[0],
      toOneRelations: (StorageModel object) => [],
      toManyRelations: (StorageModel object) => {},
      getId: (StorageModel object) => object.id,
      setId: (StorageModel object, int id) {
        object.id = id;
      },
      objectToFB: (StorageModel object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final itemNameOffset = fbb.writeString(object.itemName);
        final itemImageOffset = fbb.writeString(object.itemImage);
        fbb.startTable(12);
        fbb.addInt64(0, object.id ?? 0);
        fbb.addOffset(1, uuidOffset);
        fbb.addOffset(2, itemNameOffset);
        fbb.addOffset(3, itemImageOffset);
        fbb.addFloat64(4, object.quantity);
        fbb.addFloat64(5, object.buyPrice);
        fbb.addFloat64(6, object.sellPrice);
        fbb.addFloat64(7, object.minAmount);
        fbb.addInt64(8, object.typeIndex);
        fbb.addFloat64(10, object.paidAmount);
        fbb.finish(fbb.endTable());
        return object.id ?? 0;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          4,
        );
        final uuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final itemNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final itemImageParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final typeIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final quantityParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final buyPriceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final sellPriceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final minAmountParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final paidAmountParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final object = StorageModel(
          id: idParam,
          uuid: uuidParam,
          itemName: itemNameParam,
          itemImage: itemImageParam,
          typeIndex: typeIndexParam,
          quantity: quantityParam,
          buyPrice: buyPriceParam,
          sellPrice: sellPriceParam,
          minAmount: minAmountParam,
          paidAmount: paidAmountParam,
        );

        return object;
      },
    ),
    CustomerModel: obx_int.EntityDefinition<CustomerModel>(
      model: _entities[1],
      toOneRelations: (CustomerModel object) => [],
      toManyRelations: (CustomerModel object) => {},
      getId: (CustomerModel object) => object.id,
      setId: (CustomerModel object, int id) {
        object.id = id;
      },
      objectToFB: (CustomerModel object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final nameOffset = fbb.writeString(object.name);
        final phone1Offset = fbb.writeString(object.phone1);
        final phone2Offset = object.phone2 == null
            ? null
            : fbb.writeString(object.phone2!);
        final addressOffset = object.address == null
            ? null
            : fbb.writeString(object.address!);
        fbb.startTable(10);
        fbb.addInt64(0, object.id ?? 0);
        fbb.addOffset(1, uuidOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, phone1Offset);
        fbb.addOffset(4, phone2Offset);
        fbb.addOffset(5, addressOffset);
        fbb.addFloat64(7, object.receivableAmount);
        fbb.addFloat64(8, object.payableAmount);
        fbb.finish(fbb.endTable());
        return object.id ?? 0;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          4,
        );
        final uuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final phone1Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final phone2Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final addressParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final receivableAmountParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final payableAmountParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final object = CustomerModel(
          id: idParam,
          uuid: uuidParam,
          name: nameParam,
          phone1: phone1Param,
          phone2: phone2Param,
          address: addressParam,
          receivableAmount: receivableAmountParam,
          payableAmount: payableAmountParam,
        );

        return object;
      },
    ),
    CreateInvoiceModel: obx_int.EntityDefinition<CreateInvoiceModel>(
      model: _entities[2],
      toOneRelations: (CreateInvoiceModel object) => [
        object.customer,
        object.device,
      ],
      toManyRelations: (CreateInvoiceModel object) => {
        obx_int.RelInfo<CreateInvoiceModel>.toMany(1, object.id!): object.items,
      },
      getId: (CreateInvoiceModel object) => object.id,
      setId: (CreateInvoiceModel object, int id) {
        object.id = id;
      },
      objectToFB: (CreateInvoiceModel object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        fbb.startTable(13);
        fbb.addInt64(0, object.id ?? 0);
        fbb.addOffset(1, uuidOffset);
        fbb.addFloat64(2, object.totalInvoice);
        fbb.addFloat64(3, object.cashPaid);
        fbb.addFloat64(4, object.laterPaid);
        fbb.addInt64(5, object.invoiceDate.millisecondsSinceEpoch);
        fbb.addInt64(6, object.paymentIndex);
        fbb.addInt64(7, object.customer.targetId);
        fbb.addBool(8, object.isSession);
        fbb.addInt64(9, object.sessionStartDate?.millisecondsSinceEpoch);
        fbb.addFloat64(10, object.hourlyRate);
        fbb.addInt64(11, object.device.targetId);
        fbb.finish(fbb.endTable());
        return object.id ?? 0;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final sessionStartDateValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          22,
        );
        final idParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          4,
        );
        final uuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final totalInvoiceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final cashPaidParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final laterPaidParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final invoiceDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final paymentIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final isSessionParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          20,
          false,
        );
        final sessionStartDateParam = sessionStartDateValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(sessionStartDateValue);
        final hourlyRateParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final object = CreateInvoiceModel(
          id: idParam,
          uuid: uuidParam,
          totalInvoice: totalInvoiceParam,
          cashPaid: cashPaidParam,
          laterPaid: laterPaidParam,
          invoiceDate: invoiceDateParam,
          paymentIndex: paymentIndexParam,
          isSession: isSessionParam,
          sessionStartDate: sessionStartDateParam,
          hourlyRate: hourlyRateParam,
        );
        object.customer.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        object.customer.attach(store);
        object.device.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          26,
          0,
        );
        object.device.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<CreateInvoiceModel>(
          object.items,
          store,
          obx_int.RelInfo<CreateInvoiceModel>.toMany(1, object.id!),
        );
        return object;
      },
    ),
    ItemsInvoice: obx_int.EntityDefinition<ItemsInvoice>(
      model: _entities[3],
      toOneRelations: (ItemsInvoice object) => [object.storageItem],
      toManyRelations: (ItemsInvoice object) => {},
      getId: (ItemsInvoice object) => object.id,
      setId: (ItemsInvoice object, int id) {
        object.id = id;
      },
      objectToFB: (ItemsInvoice object, fb.Builder fbb) {
        fbb.startTable(6);
        fbb.addInt64(0, object.id ?? 0);
        fbb.addFloat64(1, object.sellPrice);
        fbb.addFloat64(2, object.quantity);
        fbb.addFloat64(3, object.totalItemPrice);
        fbb.addInt64(4, object.storageItem.targetId);
        fbb.finish(fbb.endTable());
        return object.id ?? 0;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          4,
        );
        final sellPriceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final quantityParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final totalItemPriceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final object = ItemsInvoice(
          id: idParam,
          sellPrice: sellPriceParam,
          quantity: quantityParam,
          totalItemPrice: totalItemPriceParam,
        );
        object.storageItem.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.storageItem.attach(store);
        return object;
      },
    ),
    TransactionModel: obx_int.EntityDefinition<TransactionModel>(
      model: _entities[4],
      toOneRelations: (TransactionModel object) => [],
      toManyRelations: (TransactionModel object) => {},
      getId: (TransactionModel object) => object.id,
      setId: (TransactionModel object, int id) {
        object.id = id;
      },
      objectToFB: (TransactionModel object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final userUuidOffset = fbb.writeString(object.userUuid);
        final notesOffset = object.notes == null
            ? null
            : fbb.writeString(object.notes!);
        final userNameOffset = object.userName == null
            ? null
            : fbb.writeString(object.userName!);
        final storageItemUuidOffset = object.storageItemUuid == null
            ? null
            : fbb.writeString(object.storageItemUuid!);
        fbb.startTable(15);
        fbb.addInt64(0, object.id ?? 0);
        fbb.addOffset(1, uuidOffset);
        fbb.addOffset(2, userUuidOffset);
        fbb.addFloat64(3, object.paymentAmount);
        fbb.addInt64(4, object.createdAt.millisecondsSinceEpoch);
        fbb.addOffset(5, notesOffset);
        fbb.addInt64(6, object.transactionType);
        fbb.addFloat64(7, object.beginningBalance);
        fbb.addFloat64(8, object.endBalance);
        fbb.addFloat64(9, object.invoiceProfit);
        fbb.addFloat64(10, object.paidInvoiceAmount);
        fbb.addInt64(11, object.userType);
        fbb.addOffset(12, userNameOffset);
        fbb.addOffset(13, storageItemUuidOffset);
        fbb.finish(fbb.endTable());
        return object.id ?? 0;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          4,
        );
        final uuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final userUuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final userNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 28);
        final beginningBalanceParam = const fb.Float64Reader()
            .vTableGetNullable(buffer, rootOffset, 18);
        final paymentAmountParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final paidInvoiceAmountParam = const fb.Float64Reader()
            .vTableGetNullable(buffer, rootOffset, 24);
        final endBalanceParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          20,
        );
        final invoiceProfitParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          22,
        );
        final transactionTypeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final userTypeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          26,
          0,
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final notesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final storageItemUuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 30);
        final object = TransactionModel(
          id: idParam,
          uuid: uuidParam,
          userUuid: userUuidParam,
          userName: userNameParam,
          beginningBalance: beginningBalanceParam,
          paymentAmount: paymentAmountParam,
          paidInvoiceAmount: paidInvoiceAmountParam,
          endBalance: endBalanceParam,
          invoiceProfit: invoiceProfitParam,
          transactionType: transactionTypeParam,
          userType: userTypeParam,
          createdAt: createdAtParam,
          notes: notesParam,
          storageItemUuid: storageItemUuidParam,
        );

        return object;
      },
    ),
    DeviceModel: obx_int.EntityDefinition<DeviceModel>(
      model: _entities[5],
      toOneRelations: (DeviceModel object) => [],
      toManyRelations: (DeviceModel object) => {},
      getId: (DeviceModel object) => object.id,
      setId: (DeviceModel object, int id) {
        object.id = id;
      },
      objectToFB: (DeviceModel object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(7);
        fbb.addInt64(0, object.id ?? 0);
        fbb.addOffset(1, uuidOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addFloat64(3, object.hourlyRate);
        fbb.addInt64(4, object.typeIndex);
        fbb.addInt64(5, object.statusIndex);
        fbb.finish(fbb.endTable());
        return object.id ?? 0;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          4,
        );
        final uuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final hourlyRateParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final typeIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final statusIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final object = DeviceModel(
          id: idParam,
          uuid: uuidParam,
          name: nameParam,
          hourlyRate: hourlyRateParam,
          typeIndex: typeIndexParam,
          statusIndex: statusIndexParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [StorageModel] entity fields to define ObjectBox queries.
class StorageModel_ {
  /// See [StorageModel.id].
  static final id = obx.QueryIntegerProperty<StorageModel>(
    _entities[0].properties[0],
  );

  /// See [StorageModel.uuid].
  static final uuid = obx.QueryStringProperty<StorageModel>(
    _entities[0].properties[1],
  );

  /// See [StorageModel.itemName].
  static final itemName = obx.QueryStringProperty<StorageModel>(
    _entities[0].properties[2],
  );

  /// See [StorageModel.itemImage].
  static final itemImage = obx.QueryStringProperty<StorageModel>(
    _entities[0].properties[3],
  );

  /// See [StorageModel.quantity].
  static final quantity = obx.QueryDoubleProperty<StorageModel>(
    _entities[0].properties[4],
  );

  /// See [StorageModel.buyPrice].
  static final buyPrice = obx.QueryDoubleProperty<StorageModel>(
    _entities[0].properties[5],
  );

  /// See [StorageModel.sellPrice].
  static final sellPrice = obx.QueryDoubleProperty<StorageModel>(
    _entities[0].properties[6],
  );

  /// See [StorageModel.minAmount].
  static final minAmount = obx.QueryDoubleProperty<StorageModel>(
    _entities[0].properties[7],
  );

  /// See [StorageModel.typeIndex].
  static final typeIndex = obx.QueryIntegerProperty<StorageModel>(
    _entities[0].properties[8],
  );

  /// See [StorageModel.paidAmount].
  static final paidAmount = obx.QueryDoubleProperty<StorageModel>(
    _entities[0].properties[9],
  );
}

/// [CustomerModel] entity fields to define ObjectBox queries.
class CustomerModel_ {
  /// See [CustomerModel.id].
  static final id = obx.QueryIntegerProperty<CustomerModel>(
    _entities[1].properties[0],
  );

  /// See [CustomerModel.uuid].
  static final uuid = obx.QueryStringProperty<CustomerModel>(
    _entities[1].properties[1],
  );

  /// See [CustomerModel.name].
  static final name = obx.QueryStringProperty<CustomerModel>(
    _entities[1].properties[2],
  );

  /// See [CustomerModel.phone1].
  static final phone1 = obx.QueryStringProperty<CustomerModel>(
    _entities[1].properties[3],
  );

  /// See [CustomerModel.phone2].
  static final phone2 = obx.QueryStringProperty<CustomerModel>(
    _entities[1].properties[4],
  );

  /// See [CustomerModel.address].
  static final address = obx.QueryStringProperty<CustomerModel>(
    _entities[1].properties[5],
  );

  /// See [CustomerModel.receivableAmount].
  static final receivableAmount = obx.QueryDoubleProperty<CustomerModel>(
    _entities[1].properties[6],
  );

  /// See [CustomerModel.payableAmount].
  static final payableAmount = obx.QueryDoubleProperty<CustomerModel>(
    _entities[1].properties[7],
  );
}

/// [CreateInvoiceModel] entity fields to define ObjectBox queries.
class CreateInvoiceModel_ {
  /// See [CreateInvoiceModel.id].
  static final id = obx.QueryIntegerProperty<CreateInvoiceModel>(
    _entities[2].properties[0],
  );

  /// See [CreateInvoiceModel.uuid].
  static final uuid = obx.QueryStringProperty<CreateInvoiceModel>(
    _entities[2].properties[1],
  );

  /// See [CreateInvoiceModel.totalInvoice].
  static final totalInvoice = obx.QueryDoubleProperty<CreateInvoiceModel>(
    _entities[2].properties[2],
  );

  /// See [CreateInvoiceModel.cashPaid].
  static final cashPaid = obx.QueryDoubleProperty<CreateInvoiceModel>(
    _entities[2].properties[3],
  );

  /// See [CreateInvoiceModel.laterPaid].
  static final laterPaid = obx.QueryDoubleProperty<CreateInvoiceModel>(
    _entities[2].properties[4],
  );

  /// See [CreateInvoiceModel.invoiceDate].
  static final invoiceDate = obx.QueryDateProperty<CreateInvoiceModel>(
    _entities[2].properties[5],
  );

  /// See [CreateInvoiceModel.paymentIndex].
  static final paymentIndex = obx.QueryIntegerProperty<CreateInvoiceModel>(
    _entities[2].properties[6],
  );

  /// See [CreateInvoiceModel.customer].
  static final customer =
      obx.QueryRelationToOne<CreateInvoiceModel, CustomerModel>(
        _entities[2].properties[7],
      );

  /// See [CreateInvoiceModel.isSession].
  static final isSession = obx.QueryBooleanProperty<CreateInvoiceModel>(
    _entities[2].properties[8],
  );

  /// See [CreateInvoiceModel.sessionStartDate].
  static final sessionStartDate = obx.QueryDateProperty<CreateInvoiceModel>(
    _entities[2].properties[9],
  );

  /// See [CreateInvoiceModel.hourlyRate].
  static final hourlyRate = obx.QueryDoubleProperty<CreateInvoiceModel>(
    _entities[2].properties[10],
  );

  /// See [CreateInvoiceModel.device].
  static final device = obx.QueryRelationToOne<CreateInvoiceModel, DeviceModel>(
    _entities[2].properties[11],
  );

  /// see [CreateInvoiceModel.items]
  static final items =
      obx.QueryRelationToMany<CreateInvoiceModel, ItemsInvoice>(
        _entities[2].relations[0],
      );
}

/// [ItemsInvoice] entity fields to define ObjectBox queries.
class ItemsInvoice_ {
  /// See [ItemsInvoice.id].
  static final id = obx.QueryIntegerProperty<ItemsInvoice>(
    _entities[3].properties[0],
  );

  /// See [ItemsInvoice.sellPrice].
  static final sellPrice = obx.QueryDoubleProperty<ItemsInvoice>(
    _entities[3].properties[1],
  );

  /// See [ItemsInvoice.quantity].
  static final quantity = obx.QueryDoubleProperty<ItemsInvoice>(
    _entities[3].properties[2],
  );

  /// See [ItemsInvoice.totalItemPrice].
  static final totalItemPrice = obx.QueryDoubleProperty<ItemsInvoice>(
    _entities[3].properties[3],
  );

  /// See [ItemsInvoice.storageItem].
  static final storageItem = obx.QueryRelationToOne<ItemsInvoice, StorageModel>(
    _entities[3].properties[4],
  );
}

/// [TransactionModel] entity fields to define ObjectBox queries.
class TransactionModel_ {
  /// See [TransactionModel.id].
  static final id = obx.QueryIntegerProperty<TransactionModel>(
    _entities[4].properties[0],
  );

  /// See [TransactionModel.uuid].
  static final uuid = obx.QueryStringProperty<TransactionModel>(
    _entities[4].properties[1],
  );

  /// See [TransactionModel.userUuid].
  static final userUuid = obx.QueryStringProperty<TransactionModel>(
    _entities[4].properties[2],
  );

  /// See [TransactionModel.paymentAmount].
  static final paymentAmount = obx.QueryDoubleProperty<TransactionModel>(
    _entities[4].properties[3],
  );

  /// See [TransactionModel.createdAt].
  static final createdAt = obx.QueryDateProperty<TransactionModel>(
    _entities[4].properties[4],
  );

  /// See [TransactionModel.notes].
  static final notes = obx.QueryStringProperty<TransactionModel>(
    _entities[4].properties[5],
  );

  /// See [TransactionModel.transactionType].
  static final transactionType = obx.QueryIntegerProperty<TransactionModel>(
    _entities[4].properties[6],
  );

  /// See [TransactionModel.beginningBalance].
  static final beginningBalance = obx.QueryDoubleProperty<TransactionModel>(
    _entities[4].properties[7],
  );

  /// See [TransactionModel.endBalance].
  static final endBalance = obx.QueryDoubleProperty<TransactionModel>(
    _entities[4].properties[8],
  );

  /// See [TransactionModel.invoiceProfit].
  static final invoiceProfit = obx.QueryDoubleProperty<TransactionModel>(
    _entities[4].properties[9],
  );

  /// See [TransactionModel.paidInvoiceAmount].
  static final paidInvoiceAmount = obx.QueryDoubleProperty<TransactionModel>(
    _entities[4].properties[10],
  );

  /// See [TransactionModel.userType].
  static final userType = obx.QueryIntegerProperty<TransactionModel>(
    _entities[4].properties[11],
  );

  /// See [TransactionModel.userName].
  static final userName = obx.QueryStringProperty<TransactionModel>(
    _entities[4].properties[12],
  );

  /// See [TransactionModel.storageItemUuid].
  static final storageItemUuid = obx.QueryStringProperty<TransactionModel>(
    _entities[4].properties[13],
  );
}

/// [DeviceModel] entity fields to define ObjectBox queries.
class DeviceModel_ {
  /// See [DeviceModel.id].
  static final id = obx.QueryIntegerProperty<DeviceModel>(
    _entities[5].properties[0],
  );

  /// See [DeviceModel.uuid].
  static final uuid = obx.QueryStringProperty<DeviceModel>(
    _entities[5].properties[1],
  );

  /// See [DeviceModel.name].
  static final name = obx.QueryStringProperty<DeviceModel>(
    _entities[5].properties[2],
  );

  /// See [DeviceModel.hourlyRate].
  static final hourlyRate = obx.QueryDoubleProperty<DeviceModel>(
    _entities[5].properties[3],
  );

  /// See [DeviceModel.typeIndex].
  static final typeIndex = obx.QueryIntegerProperty<DeviceModel>(
    _entities[5].properties[4],
  );

  /// See [DeviceModel.statusIndex].
  static final statusIndex = obx.QueryIntegerProperty<DeviceModel>(
    _entities[5].properties[5],
  );
}
