// ignore_for_file: avoid_print

import 'dart:io';

/// Complete working build script
/// 1. Compiles SVG to .vec files
/// 2. Generates asset constants (custom generator - no packages needed!)
///
/// Run with: fvm dart run tool/build_assets.dart
Future<void> main() async {
  print('╔═══════════════════════════════════════════════╗');
  print('║     Complete Assets Build                     ║');
  print('╚═══════════════════════════════════════════════╝\n');

  // Step 1: Compile Vector Graphics
  print('📦 Step 1: Compiling Vector Graphics');
  print('─────────────────────────────────────────────────\n');

  final compileSuccess = await _compileVectorGraphics();

  if (!compileSuccess) {
    print('\n❌ Vector graphics compilation failed!');
    exit(1);
  }

  print('\n✅ Vector graphics compilation complete!\n');

  // Step 2: Generate Asset Constants
  print('📝 Step 2: Generating Asset Constants');
  print('─────────────────────────────────────────────────\n');

  await _generateAssetConstants();

  print('\n✅ Asset constants generation complete!\n');

  // Summary
  print('╔═══════════════════════════════════════════════╗');
  print('║     Build Complete! 🎉                        ║');
  print('╚═══════════════════════════════════════════════╝');
  print('\n📝 Generated files:');
  print('   • assets/icons/vec/*.vec (5 icons)');
  print('   • lib/core/constants/app_assets.dart');
  print('\n💡 Usage example:');
  print(
    '   import \'package:responsive_drawer/core/constants/app_assets.dart\';',
  );
  print('');
  print('   VectorGraphic(');
  print('     loader: AssetBytesLoader(VectorIcons.home),');
  print('     width: 24,');
  print('     height: 24,');
  print('   )');
  print('');
}

Future<bool> _compileVectorGraphics() async {
  final sourceDir = Directory('assets/icons/svg');
  final outputDir = Directory('assets/icons/vec');

  if (!sourceDir.existsSync()) {
    print('⚠️  Source directory not found: ${sourceDir.path}');
    return false;
  }

  if (!outputDir.existsSync()) {
    print('📁 Creating output directory: ${outputDir.path}');
    outputDir.createSync(recursive: true);
  }

  final svgFiles = sourceDir
      .listSync(recursive: true)
      .whereType<File>()
      .where((file) => file.path.endsWith('.svg'))
      .toList();

  if (svgFiles.isEmpty) {
    print('⚠️  No SVG files found in ${sourceDir.path}');
    return true;
  }

  print('Found ${svgFiles.length} SVG file(s)\n');

  int successCount = 0;
  int failureCount = 0;

  for (var i = 0; i < svgFiles.length; i++) {
    final svgFile = svgFiles[i];
    final fileName = svgFile.uri.pathSegments.last;
    final outputPath = '${outputDir.path}/${fileName.replaceAll('.svg', '.vec')}';

    print('[${i + 1}/${svgFiles.length}] Compiling $fileName...');

    try {
      final result = await Process.run('dart', [
        'run',
        'vector_graphics_compiler',
        '-i',
        svgFile.path,
        '-o',
        outputPath,
      ]);

      if (result.exitCode == 0) {
        print('    ✓ $fileName.vec');
        successCount++;
      } else {
        print('    ✗ Failed: ${result.stderr}');
        failureCount++;
      }
    } catch (e) {
      print('    ✗ Error: $e');
      failureCount++;
    }
  }

  print('\n📊 Summary: $successCount succeeded, $failureCount failed');
  return failureCount == 0;
}

Future<void> _generateAssetConstants() async {
  final code = StringBuffer();

  // File header
  code.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
  code.writeln('// Generated by: tool/build_assets.dart');
  code.writeln('// Generated on: ${DateTime.now().toIso8601String()}');
  code.writeln();
  code.writeln('// ignore_for_file: constant_identifier_names');
  code.writeln('// ignore_for_file: lines_longer_than_80_chars');
  code.writeln();

  // Generate VectorIcons class
  await _generateVectorIcons(code);

  code.writeln();

  // Generate AppImages class
  await _generateAppImages(code);

  code.writeln();

  // Generate AppTranslations class
  await _generateAppTranslations(code);

  // Generate AppLottie class
  await _generateAppLottie(code);

  // Write to file
  final outputFile = File('lib/core/constants/app_assets.dart');

  if (!outputFile.parent.existsSync()) {
    outputFile.parent.createSync(recursive: true);
  }

  await outputFile.writeAsString(code.toString());

  print('✓ Generated: ${outputFile.path}');
}

Future<void> _generateVectorIcons(StringBuffer code) async {
  final vecDir = Directory('assets/icons/vec');

  code.writeln('/// Vector graphic icon paths');
  code.writeln('class VectorIcons {');
  code.writeln('  VectorIcons._();');
  code.writeln();

  if (vecDir.existsSync()) {
    final vecFiles =
        vecDir
            .listSync()
            .whereType<File>()
            .where((file) => file.path.endsWith('.vec'))
            .toList()
          ..sort((a, b) => a.path.compareTo(b.path));

    if (vecFiles.isNotEmpty) {
      for (var file in vecFiles) {
        final fileName = file.uri.pathSegments.last;
        // Convert: exams.svg.vec -> exams
        final iconName = _toCamelCase(fileName.replaceAll('.vec', ''));
        final path = 'assets/icons/vec/$fileName';

        code.writeln('  /// $fileName');
        code.writeln('  static const String $iconName = \'$path\';');
        code.writeln();
      }

      print('  ✓ Generated ${vecFiles.length} vector icon(s)');
    } else {
      code.writeln('  // No vector icons found');
      code.writeln();
      print('  ⚠️  No vector icons found');
    }
  } else {
    code.writeln('  // assets/icons/vec directory not found');
    code.writeln();
    print('  ⚠️  assets/icons/vec directory not found');
  }

  code.writeln('}');
}

Future<void> _generateAppImages(StringBuffer code) async {
  final imagesDir = Directory('assets/images');

  code.writeln('/// Application image paths');
  code.writeln('class AppImages {');
  code.writeln('  AppImages._();');
  code.writeln();

  if (imagesDir.existsSync()) {
    final imageFiles = imagesDir.listSync().whereType<File>().where((file) {
      final ext = file.path.split('.').last.toLowerCase();
      return ['png', 'jpg', 'jpeg', 'webp', 'gif', 'bmp'].contains(ext);
    }).toList()..sort((a, b) => a.path.compareTo(b.path));

    if (imageFiles.isNotEmpty) {
      for (var file in imageFiles) {
        final fileName = file.uri.pathSegments.last;
        final imageName = _toCamelCase(fileName.split('.').first);
        final path = 'assets/images/$fileName';

        code.writeln('  /// $fileName');
        code.writeln('  static const String $imageName = \'$path\';');
        code.writeln();
      }

      print('  ✓ Generated ${imageFiles.length} image(s)');
    } else {
      code.writeln('  // No images found');
      code.writeln();
      print('  ⚠️  No images found in assets/images');
    }
  } else {
    code.writeln('  // assets/images directory not found');
    code.writeln();
    print('  ⚠️  assets/images directory not found');
  }

  code.writeln('}');
}

Future<void> _generateAppTranslations(StringBuffer code) async {
  final translationsDir = Directory('assets/translations');

  code.writeln('/// Translation file paths');
  code.writeln('class AppTranslations {');
  code.writeln('  AppTranslations._();');
  code.writeln();

  if (translationsDir.existsSync()) {
    final translationFiles =
        translationsDir
            .listSync()
            .whereType<File>()
            .where((file) => file.path.endsWith('.json'))
            .toList()
          ..sort((a, b) => a.path.compareTo(b.path));

    if (translationFiles.isNotEmpty) {
      for (var file in translationFiles) {
        final fileName = file.uri.pathSegments.last;
        final langName = _toCamelCase(fileName.replaceAll('.json', ''));
        final path = 'assets/translations/$fileName';

        code.writeln('  /// $fileName');
        code.writeln('  static const String $langName = \'$path\';');
        code.writeln();
      }

      print('  ✓ Generated ${translationFiles.length} translation(s)');
    } else {
      code.writeln('  // No translation files found');
      code.writeln();
      print('  ⚠️  No translation files found');
    }
  } else {
    code.writeln('  // assets/translations directory not found');
    code.writeln();
    print('  ⚠️  assets/translations directory not found');
  }

  code.writeln('}');
}

Future<void> _generateAppLottie(StringBuffer code) async {
  final lottieDir = Directory('assets/lottie');

  code.writeln('/// Lottie animation file paths');
  code.writeln('class AppLottie {');
  code.writeln('  AppLottie._();');
  code.writeln();

  if (lottieDir.existsSync()) {
    final lottieFiles =
        lottieDir
            .listSync()
            .whereType<File>()
            .where((file) => file.path.endsWith('.json'))
            .toList()
          ..sort((a, b) => a.path.compareTo(b.path));

    if (lottieFiles.isNotEmpty) {
      for (var file in lottieFiles) {
        final fileName = file.uri.pathSegments.last;
        final animationName = _toCamelCase(fileName.replaceAll('.json', ''));
        final path = 'assets/lottie/$fileName';

        code.writeln('  /// $fileName');
        code.writeln('  static const String $animationName = \'$path\';');
        code.writeln();
      }

      print('  ✓ Generated ${lottieFiles.length} lottie animation(s)');
    } else {
      code.writeln('  // No lottie animations found');
      code.writeln();
      print('  ⚠️  No lottie animations found in assets/lottie');
    }
  } else {
    code.writeln('  // assets/lottie directory not found');
    code.writeln();
    print('  ⚠️  assets/lottie directory not found');
  }

  code.writeln('}');
}

/// Convert filename to camelCase
/// Examples:
///   home -> home
///   home-icon -> homeIcon
///   home_icon -> homeIcon
///   HomeIcon -> homeIcon
String _toCamelCase(String input) {
  if (input.isEmpty) return input;

  // Replace hyphens and underscores with spaces
  final normalized = input
      .replaceAll(RegExp(r'[-_]'), ' ')
      .toLowerCase()
      .trim();

  // Split into words
  final words = normalized.split(RegExp(r'\s+'));

  if (words.isEmpty) return input;

  // First word lowercase, rest capitalized
  return words.first +
      words.skip(1).map((word) {
        if (word.isEmpty) return '';
        return word[0].toUpperCase() + word.substring(1);
      }).join();
}
