// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by: tool/build_assets.dart
// Generated on: 2026-07-03T14:38:16.821557

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

/// Vector graphic icon paths
class VectorIcons {
  VectorIcons._();

  /// arrows.vec
  static const String arrows = 'assets/icons/vec/arrows.vec';

  /// customer.vec
  static const String customer = 'assets/icons/vec/customer.vec';

  /// drive_export.vec
  static const String driveExport = 'assets/icons/vec/drive_export.vec';

  /// gamepad.vec
  static const String gamepad = 'assets/icons/vec/gamepad.vec';

  /// google.vec
  static const String google = 'assets/icons/vec/google.vec';

  /// home.vec
  static const String home = 'assets/icons/vec/home.vec';

  /// inventory.vec
  static const String inventory = 'assets/icons/vec/inventory.vec';

  /// profit.vec
  static const String profit = 'assets/icons/vec/profit.vec';

  /// qr.vec
  static const String qr = 'assets/icons/vec/qr.vec';

  /// receipt.vec
  static const String receipt = 'assets/icons/vec/receipt.vec';

  /// save.vec
  static const String save = 'assets/icons/vec/save.vec';

  /// supplier.vec
  static const String supplier = 'assets/icons/vec/supplier.vec';

  /// transactions.vec
  static const String transactions = 'assets/icons/vec/transactions.vec';

}

/// Application image paths
class AppImages {
  AppImages._();

  /// contact_qr.png
  static const String contactQr = 'assets/images/contact_qr.png';

  /// logo.png
  static const String logo = 'assets/images/logo.png';

}

/// Translation file paths
class AppTranslations {
  AppTranslations._();

  /// ar.json
  static const String ar = 'assets/translations/ar.json';

  /// en.json
  static const String en = 'assets/translations/en.json';

  /// lang.json
  static const String lang = 'assets/translations/lang.json';

}
/// Lottie animation file paths
class AppLottie {
  AppLottie._();

  // assets/lottie directory not found

}
